# Generated by Django 4.1.4 on 2022-12-27 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(max_length=100)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='descripcion de la pelicula', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('sinopsis', models.TextField(help_text='resumen de la pelicula', max_length=100)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.director')),
                ('genre', models.ManyToManyField(to='cine.genre')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDeLaPelicula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificacion de la pelicula', primary_key=True, serialize=False)),
                ('estreno', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('EA', 'ESTE AÑO'), ('NE', 'NO ESTRENADA')], help_text='estado de la pelicula', max_length=15)),
                ('pelicula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.pelicula')),
            ],
        ),
    ]
