# Generated by Django 4.1.4 on 2022-12-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='director',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='director',
            name='fecha_de_nacimiento',
        ),
        migrations.AddField(
            model_name='director',
            name='descripcion',
            field=models.CharField(default='pelicula', help_text='describa de que trata la pelicula', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='titulo',
            field=models.CharField(default='titulo', help_text='nombre de la pelicula', max_length=100),
        ),
        migrations.AlterField(
            model_name='director',
            name='primer_nombre',
            field=models.CharField(default='pedro', help_text='nombre del director', max_length=100),
        ),
        migrations.AlterField(
            model_name='director',
            name='segundo_nombre',
            field=models.CharField(default='perez', help_text='apellido del director', max_length=100),
        ),
        migrations.DeleteModel(
            name='EstadoDeLaPelicula',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
    ]
